#!/bin/sh
# Debug state scripts

RETRY_LATER=21
OK=0
ABORT=1

log() {
    echo "$*" >&2
    echo "$*" >>/data/debug-state-script.txt
}

log ""
log "==============================================================="
log "$(cat /etc/mender/artifact_info): $(basename "$0") was called!"
log "$(mount | grep ext)"
log "$(pstree)"

case $(basename "$0") in
    *ArtifactCommit_Enter* ) [ -e "/tmp/commit-failure" ] && log "ABORTING" && exit ${ABORT};;
esac

exit ${OK}
