#!/bin/sh

RETRY_LATER=21
OK=0
ABORT=1

log() {
    echo "stderr:$*" >&2
    echo "$*" >> /data/state-script-logging.txt
    wall "$*"
}

log "$(cat /etc/mender/artifact_info): $(basename "$0") was called!"

log "Exiting $(basename "$0") with RC ${RC}"
exit ${RC}
